apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: character-builder-ui
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: eu.gcr.io/web3-335312/character-builder/staging/ui
      docker:
        dockerfile: Dockerfile.ui
        buildArgs:
          REACT_APP_DAPP_CONSTANTS_JSON: "" # TODO: provide actual value
deploy:
  kustomize:
    paths:
      - ../deployment/staging/workloads
    defaultNamespace: character-builder-staging
